# Varia Suit Monokai
#
# Recommended terminal emulator settings
#
# Font
#
# Atkinson Hyperlegible Mono
# https://fonts.google.com/specimen/Atkinson+Hyperlegible+Mono
#
# Colors
#
# * Window Background:           #221F23
# * Window Foreground Text:      #797979
# * Window Foreground Bold Text: #ACACAC
# * Cursor Background:           #FED254
# * Cursor Foreground:           #221F23
# * Selection Foreground:        #4D4D4D
# * Selection Background:        #221F23
#
# Recommended zsh settings
#
# * PROMPT:         190 8 bit ANSI decimal # 24 bit #D7FF00
# * zle_highlight:  190 8 bit ANSI decimal # 24 bit #D7FF00
#
# Install:
#
# cp starship.toml ~/.config/starship.toml
#
# Uninstall:
#
# rm ~/.config/starship.toml
#
# Inspiration:
#
# https://archive.org/details/metroid-dread-special-edition-artbook
# https://colorhunt.co/palette/fff58affbbe1dd7bdfb3bfff
#
# See also pastel for transformation between color code formats:
# https://github.com/sharkdp/pastel

"$schema" = 'https://starship.rs/config-schema.json'

format = """$jobs$character"""

right_format = """$username$hostname$directory$status"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = 'fg:5' # 24 bit #800080
style_root = 'fg:5' # 24 bit #800080
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = 'fg:5'      # 24 bit #800080
format = '[@$hostname:]($style)'

[directory]
style = 'fg:5'      # 24 bit #800080
format = '[$path]($style)'
truncation_length = 1

[status]
disabled = false
pipestatus = true
style = 'fg:1'      # 24 bit #800000
format = '[ ! $status]($style)'
pipestatus_segment_format = '[$status]($style)'
pipestatus_format = '[ $pipestatus]($style)'

[character]
success_symbol = "%"
error_symbol = "%"
format = "[$symbol](fg:190) " # 24 bit #D7FF00
