# Varia Suit
#
# Recommended terminal emulator colors:
#
# * Window Background: #0F0F0F
# * Window Foreground: #4CB73F
# * Cursor Background: #4CB73F
# * Cursor Foreground: #0F0F0F
#
# Recommended zsh colors:
#
# * zle_highlight: #4CB73F
#
# Install:
#
# cp starship.toml ~/.config/starship.toml
#
# Uninstall:
#
# rm ~/.config/starship.toml
#
# Inspiration:
#
# https://archive.org/details/metroid-dread-special-edition-artbook
# https://colorhunt.co/palette/fff58affbbe1dd7bdfb3bfff

"$schema" = 'https://starship.rs/config-schema.json'

format = """$jobs$character"""

right_format = """$username$hostname$directory$status"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = 'fg:#D7FF00'
style_root = 'fg:#D7FF00'
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = 'fg:#D7FF00'
format = '[@$hostname:]($style)'

[directory]
style = 'fg:#D7FF00'
format = '[$path]($style)'
truncation_length = 1

[status]
disabled = false
pipestatus = true
style = 'fg:#FF8A8A'
format = '[ ! $status]($style)'
pipestatus_segment_format = '[$status]($style)'
pipestatus_format = '[ $pipestatus]($style)'

[character]
success_symbol = "%"
error_symbol = "%"
format = "[$symbol](fg:#4CB73F bold) "
