#
# Install:
#
# cp starship.toml ~/.config/starship.toml
#
# Uninstall:
#
# rm ~/.config/starship.toml


"$schema" = 'https://starship.rs/config-schema.json'

format = """$jobs$character"""

right_format = """$username$hostname$directory$status"""

palette = "monokai"

# Disable the blank line at the start of the prompt
add_newline = false

#
# Colors expressed in sRGB.
#

[palettes.monokai]
context = "#ff00ff" # sRGB ; 8 bit ANSI 201
error   = "#800000" # sRGB ; 8 bit ANSI 1
# prompt  = "#afd700" # sRGB ; 8 bit ANSI 147

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = 'fg:context'
style_root = 'fg:context'
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = 'fg:context'
format = '[@$hostname:]($style)'

[directory]
style = 'fg:context'
format = '[$path]($style)'
truncation_length = 1

[status]
disabled = false
pipestatus = true
style = 'fg:error'
format = '[ ! $status]($style)'
pipestatus_segment_format = '[$status]($style)'
pipestatus_format = '[ $pipestatus]($style)'

# [character]
# success_symbol = "%"
# error_symbol = "%"
# format = "[$symbol](fg:prompt) "

# Recommended terminal emulator settings
#
# Font Family
#
# Atkinson Hyperlegible Mono ExtraLight Light (Apple Terminal)
# Atkinson Hyperlegible Mono Regular (iTerm2)
#
# https://fonts.google.com/specimen/Atkinson+Hyperlegible+Mono
#
# * Window Background:             #1c1c1c ; sRGB ; 8 bit ANSI 234
# * Window Foreground Text:        #6c6c6c ; sRGB ; 8 bit ANSI 242
# * Window Foreground Bold Text:   #a8a8a8 ; sRGB ; 8 bit ANSI 248
# * Cursor (Apple Terminal):       #afd700 ; sRGB ; 8 bit ANSI 148
# * Cursor (Background iTerm2):    #a5d600 ; sRGB
# * Cursor (Foreground iTerm2):    #1c1c1c ; sRGB ; 8 bit ANSI 234
# * Selection (Apple Terminal):    #3a3a3a ; sRGB ; 8 bit ANSI 237
# * Selection Background (iTerm2): #6c6c6c ; sRGB ; 8 bit ANSI 242
# * Selection Foreground (iTerm2): #1c1c1c ; sRGB ; 8 bit ANSI 234
#
# Terminal Theme
#
# "Black"         #000000 ; sRGB ; 8 bit ANSI 0
# "Red"           #af0000 ; sRGB ; 8 bit ANSI 124
# "Green"         #00A600 ; sRGB ; 8 bit ANSI 34
# "Yellow"        #0087ff ; sRGB ; 8 bit ANSI 33
# "Blue"          #5f00ff ; sRGB ; 8 bit ANSI 57
# "Purple"        #af00d7 ; sRGB ; 8 bit ANSI 128
# "Cyan"          #d78700 ; sRGB ; 8 bit ANSI 172
# "White"         #bcbcbc ; sRGB ; 8 bit ANSI 250
#
# "Bright Black"  #303030 ; sRGB ; 8 bit ANSI 236
# "Bright Red"    #ff0000 ; sRGB ; 8 bit ANSI 160
# "Bright Green"  #00d700 ; sRGB ; 8 bit ANSI 40
# "Bright Yellow" #00afff ; sRGB ; 8 bit ANSI 39
# "Bright Blue"   #8700FF ; sRGB ; 8 bit ANSI 93
# "Bright Purple" #d700ff ; sRGB ; 8 bit ANSI 165
# "Bright Cyan"   #FFAF00 ; sRGB ; 8 bit ANSI 214
# "Bright White"  #E4E4E4 ; sRGB ; 8 bit ANSI 254
#
# Inspiration:
#
# https://monokai.pro/
#
# Browse ColorPalette for 8 bit ANSI compatible color schemes
# https://hexdocs.pm/color_palette/ansi_color_codes.html
#
# See also pastel for transformation between color code formats:
# https://github.com/sharkdp/pastel
