# Varia Suit Monokai

"$schema" = 'https://starship.rs/config-schema.json'

format = """$jobs$character"""

right_format = """$username$hostname$directory$status"""

palette = "monokai"

# Disable the blank line at the start of the prompt
add_newline = false

[palettes.monokai]
context = "13"  # 8 bit ANSI. 24 bit #FF00FF
error   = "1"   # 8 bit ANSI. 24 bit #800000
prompt  = "190" # 8 bit ANSI. 24 bit #D7FF00

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = 'fg:context'
style_root = 'fg:context'
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = 'fg:context'
format = '[@$hostname:]($style)'

[directory]
style = 'fg:context'
format = '[$path]($style)'
truncation_length = 1

[status]
disabled = false
pipestatus = true
style = 'fg:error'
format = '[ ! $status]($style)'
pipestatus_segment_format = '[$status]($style)'
pipestatus_format = '[ $pipestatus]($style)'

[character]
success_symbol = "%"
error_symbol = "%"
format = "[$symbol](fg:prompt) "

# Recommended terminal emulator settings
#
# Font
#
# Atkinson Hyperlegible Mono
# https://fonts.google.com/specimen/Atkinson+Hyperlegible+Mono
#
# Colors
#
# * Window Background:           #221F23
# * Window Foreground Text:      #797979
# * Window Foreground Bold Text: #ACACAC
# * Cursor Background:           #FED254
# * Cursor Foreground:           #221F23
# * Selection Foreground:        #4D4D4D
# * Selection Background:        #221F23
#
# Recommended zsh settings
#
# * PROMPT:                        (match palettes.monokai.prompt)
# * zle_highlight:                 (match palettes.monokai.prompt)
#
# Install:
#
# cp starship.toml ~/.config/starship.toml
#
# Uninstall:
#
# rm ~/.config/starship.toml
#
# Inspiration:
#
# https://monokai.pro/
#
# Browse ColorPalette for 8 bit ANSI, macOS Terminal.app compatible color schemes
# https://hexdocs.pm/color_palette/ansi_color_codes.html
#
# See also pastel for transformation between color code formats:
# https://github.com/sharkdp/pastel
